# Generated by Django 4.2.1 on 2023-05-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_info',
            old_name='title',
            new_name='topic',
        ),
    ]
