# Generated by Django 4.2.1 on 2023-05-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0002_rename_title_post_info_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_info',
            name='images',
            field=models.FileField(blank=True, upload_to='midea/images'),
        ),
    ]
